blog/urls.py
from django.urls import path
from . import views
from .views import BlogListView, BlogDetailView, SharePost

app_name = 'blog'

urlpatterns = [
    path('', BlogListView.as_view(), name='list'),
    path('<int:year>/<int:month>/<int:day>/<str:slug>/', BlogDetailView.as_view(), name='blog-item'),
    path('d/<int:pk>/', BlogDetailView.as_view(), name='blog-item'),
    path('categories', views.categories_view),
    path('share/<int:pk>', views.SharePost.as_view(), name='share-post')
]

djangoProject/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('blog.urls', 'blog'), namespace='blog')),
    path('accounts/', include('django.contrib.auth.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.conf import settings
from django.urls import reverse


# Create your models here.
class Category(models.Model):
    title = models.CharField(verbose_name=_("title"), max_length=255)
    active = models.BooleanField(verbose_name=_("active"), default=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = _("category")
        verbose_name_plural = _("categories")


class Post(models.Model):

    class StatusChoices(models.TextChoices):
        DRAFT = 'DF', 'Draft'
        PUBLISHED = 'PB', 'Published'

    title = models.CharField(verbose_name=_("title"), max_length=255)
    thumbnail = models.ImageField(verbose_name=_("thumb"), null=True, upload_to='posts/')
    slug = models.SlugField(verbose_name=_("slug"), allow_unicode=True, null=False, unique_for_date="publish_time")
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True)
    lead = models.CharField(verbose_name=_("Lead"), max_length=1024, null=True, blank=True)
    body = models.TextField(verbose_name=_("body"))
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, blank=True)

    created = models.DateTimeField(verbose_name=_("created"), auto_now_add=True)
    updated = models.DateTimeField(verbose_name=_("updated"), auto_now=True)

    status = models.CharField(verbose_name=_("status"), max_length=15, choices=StatusChoices.choices,
                              default=StatusChoices.DRAFT)
    featured = models.BooleanField(verbose_name=_("featured"), null=True)
    publish_time = models.DateTimeField(verbose_name=_("publish time"), null=True, blank=True)

    def get_absolute_url(self):
        return reverse('blog:blog-item', args=[
            self.publish_time.year,
            self.publish_time.month,
            self.publish_time.day,
            self.slug
        ])

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = _("post")
        verbose_name_plural = _("posts")
        ordering = ["-publish_time"]

class Comment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(verbose_name=_("created"), auto_now_add=True)
    updated = models.DateTimeField(verbose_name=_("updated"), auto_now=True)
    approved = models.BooleanField()

    def __str__(self):
        return self.name

class SiteUser(AbstractUser):
    pass

blog/forms.py
from django import forms

from .models import *


class ShareForm(forms.Form):
    name = forms.CharField(max_length=50)
    email = forms.EmailField()
    to = forms.EmailField()
    description = forms.CharField(required=False, widget=forms.Textarea)

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        exclude = ['created', 'updated', 'approved', 'post', 'user']

blog/views.py
from django.core.mail import send_mail
from django.views import View
from django.views.generic import ListView, DetailView
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from .forms import *
from .models import *


# Create your views here.

def list_view(request):
    posts = Post.objects.filter(status=Post.StatusChoices.PUBLISHED, publish_time__lte=timezone.now())
    return render(request, 'blog/list.html', {'posts': posts})


class BlogListView(ListView):
    template_name = 'blog/list.html'
    # model = Post
    queryset = Post.objects.filter(status=Post.StatusChoices.PUBLISHED)
    context_object_name = 'posts'


def detail_view(request, year, month, day, slug):
    post = get_object_or_404(Post, status=Post.StatusChoices.PUBLISHED, publish_time__year=year,
                             publish_time__month=month,
                             publish_time__day=day, slug=slug)
    return render(request, 'blog/detail.html', {'post': post})


class BlogDetailView(DetailView):
    model = Post
    template_name = 'blog/detail.html'

    def get_object(self, queryset=None):
        return Post.objects.get(status=Post.StatusChoices.PUBLISHED, publish_time__year=self.kwargs['year'],
                                publish_time__month=self.kwargs['month'],
                                publish_time__day=self.kwargs['day'], slug=self.kwargs['slug'])

    def get_context_data(self, **kwargs):
        context = super(BlogDetailView, self).get_context_data()
        context['comments'] = Comment.objects.filter(post=self.get_object(), approved=True)
        context['comments_form'] = CommentForm()
        return context

    def post(self, request, year, month, day, slug):
        post = self.get_object()
        comment_data = CommentForm(request.POST)
        if comment_data.is_valid():
            comment = Comment(post=post,
                              user=request.user,
                              name=comment_data.cleaned_data.get('name'),
                              email=comment_data.cleaned_data.get('email'),
                              body=comment_data.cleaned_data.get('body'),
                              approved=False
                              )
            comment.save()
            self.object = self.get_object()
            return self.render_to_response(context=self.get_context_data())
        else:
            self.object = self.get_object()
            context = self.get_context_data()
            context['comments_form'] = comment_data
            return self.render_to_response(context=context)


def categories_view(request):
    categories = Category.objects.all()
    return render(request, 'blog/categories.html', {'categories': categories})


class SharePost(View):
    def get(self, request, pk):
        form = ShareForm()
        post = get_object_or_404(Post, pk=pk)
        return render(request, 'blog/share.html', {'form': form, 'post': post})

    def post(self, request, pk):
        post = get_object_or_404(Post, pk=pk)
        form = ShareForm(request.POST)
        if form.is_valid():
            send_mail(
                "Sharing a post".format(post.title),
                form.cleaned_data.get('comment'),
                form.cleaned_data.get('email'),
                form.cleaned_data.get('to'),
                fail_silently=False,
            )
            return redirect(post.get_absolute_url())
        else:
            return render(request, 'blog/share.html', {'form': form, 'post': post})

templates/base.html
{% load humanize %}
{% load static %}
<!DOCTYPE html>
<html lang="en"> 
<head>
    <title>Blog{% block title %} {% endblock %}</title>
    
    <!-- Meta -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Blog Template">
    <meta name="author" content="Xiaoying Riley at 3rd Wave Media">    
    <link rel="shortcut icon" href="{% static 'favicon.ico' %}"> 
    
    <!-- FontAwesome JS-->
    <script defer src="https://use.fontawesome.com/releases/v5.7.1/js/all.js" integrity="sha384-eVEQC9zshBn0rFj4+TU78eNA19HMNigMviK/PU/FFjLXqa/GKPgX58rvt5Z8PLs7" crossorigin="anonymous"></script>
    
    <!-- Plugin CSS -->
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.14.2/styles/monokai-sublime.min.css">
    
    <!-- Theme CSS -->  
    <link id="theme-style" rel="stylesheet" href="{% static 'assets/css/theme-1.css' %}">
    {% block headerextra %} {% endblock %}
    

</head> 

<body>
    
    <header class="header text-center">	    
	    <h1 class="blog-name pt-lg-4 mb-0"><a href="/">Sajjad's Blog</a></h1>
        
	    <nav class="navbar navbar-expand-lg navbar-dark" >
           
			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navigation" aria-controls="navigation" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
			</button>

			<div id="navigation" class="collapse navbar-collapse flex-column" >
				<div class="profile-section pt-3 pt-lg-0">
				    <img class="profile-image mb-3 rounded-circle mx-auto" src="{% static 'assets/images/profile.png' %}" alt="image" >			
					
					<div class="bio mb-3">Hi, my name is Sajjad. Briefly introduce yourself here. You can also provide a link to the about page.<br><a href="https://github.com/SajjadSj66">Find out more about me</a></div><!--//bio-->
					<ul class="social-list list-inline py-3 mx-auto">
			            <li class="list-inline-item"><a href="#"><i class="fab fa-twitter fa-fw"></i></a></li>
			            <li class="list-inline-item"><a href="#"><i class="fab fa-linkedin-in fa-fw"></i></a></li>
			            <li class="list-inline-item"><a href="#"><i class="fab fa-github-alt fa-fw"></i></a></li>
			            <li class="list-inline-item"><a href="#"><i class="fab fa-stack-overflow fa-fw"></i></a></li>
			            <li class="list-inline-item"><a href="#"><i class="fab fa-codepen fa-fw"></i></a></li>
			        </ul><!--//social-list-->
			        <hr> 
				</div><!--//profile-section-->
				
				<ul class="navbar-nav flex-column text-left">
					<li class="nav-item">
					    <a class="nav-link" href="blog/list.html"><i class="fas fa-home fa-fw mr-2"></i>Blog Home <span class="sr-only">(current)</span></a>
					</li>
					<li class="nav-item active">
					    <a class="nav-link" href="blog/blog-post.html"><i class="fas fa-bookmark fa-fw mr-2"></i>Blog Post</a>
					</li>
					<li class="nav-item">
					    <a class="nav-link" href="blog/about.html"><i class="fas fa-user fa-fw mr-2"></i>About Me</a>
					</li>
				</ul>
				
				<div class="my-2 my-md-3">
					
				    <a class="btn btn-primary" href="https://themes.3rdwavemedia.com/" target="_blank">Get in Touch</a>
				    
				</div>
			</div>
		</nav>
    </header>
    
    <div class="main-wrapper">
          {% block content %} {% endblock %}
    </div><!--//main-wrapper-->
    

    <!-- *****CONFIGURE STYLE (REMOVE ON YOUR PRODUCTION SITE)****** -->  
    {% include "switcher.html" %}

    
    {% include "footer.html" %}
    <!-- Custom JS -->
  
    

</body>
</html> 

templates/blog/about.html
<!DOCTYPE html>
<html lang="en"> 
<head>
    <title>Bootstrap 4 Blog Template For Developers</title>
    
    <!-- Meta -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Blog Template">
    <meta name="author" content="Xiaoying Riley at 3rd Wave Media">    
    <link rel="shortcut icon" href="favicon.ico"> 
    
    <!-- FontAwesome JS-->
    <script defer src="https://use.fontawesome.com/releases/v5.7.1/js/all.js" integrity="sha384-eVEQC9zshBn0rFj4+TU78eNA19HMNigMviK/PU/FFjLXqa/GKPgX58rvt5Z8PLs7" crossorigin="anonymous"></script>
    
    <!-- Theme CSS -->  
    <link id="theme-style" rel="stylesheet" href="assets/css/theme-1.css">
    

</head> 

<body>
    
    <header class="header text-center">	    
	    <h1 class="blog-name pt-lg-4 mb-0"><a href="index.html">Anthony's Blog</a></h1>
        
	    <nav class="navbar navbar-expand-lg navbar-dark" >
           
			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navigation" aria-controls="navigation" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
			</button>

			<div id="navigation" class="collapse navbar-collapse flex-column" >
				<div class="profile-section pt-3 pt-lg-0">
				    <img class="profile-image mb-3 rounded-circle mx-auto" src="assets/images/profile.png" alt="image" >			
					
					<div class="bio mb-3">Hi, my name is Anthony Doe. Briefly introduce yourself here. You can also provide a link to the about page.<br><a href="about.html">Find out more about me</a></div><!--//bio-->
					<ul class="social-list list-inline py-3 mx-auto">
			            <li class="list-inline-item"><a href="#"><i class="fab fa-twitter fa-fw"></i></a></li>
			            <li class="list-inline-item"><a href="#"><i class="fab fa-linkedin-in fa-fw"></i></a></li>
			            <li class="list-inline-item"><a href="#"><i class="fab fa-github-alt fa-fw"></i></a></li>
			            <li class="list-inline-item"><a href="#"><i class="fab fa-stack-overflow fa-fw"></i></a></li>
			            <li class="list-inline-item"><a href="#"><i class="fab fa-codepen fa-fw"></i></a></li>
			        </ul><!--//social-list-->
			        <hr> 
				</div><!--//profile-section-->
				
				<ul class="navbar-nav flex-column text-left">
					<li class="nav-item">
					    <a class="nav-link" href="index.html"><i class="fas fa-home fa-fw mr-2"></i>Blog Home <span class="sr-only">(current)</span></a>
					</li>
					<li class="nav-item">
					    <a class="nav-link" href="blog-post.html"><i class="fas fa-bookmark fa-fw mr-2"></i>Blog Post</a>
					</li>
					<li class="nav-item active">
					    <a class="nav-link" href="about.html"><i class="fas fa-user fa-fw mr-2"></i>About Me</a>
					</li>
				</ul>
				
				<div class="my-2 my-md-3">
					
				    <a class="btn btn-primary" href="https://themes.3rdwavemedia.com/" target="_blank">Get in Touch</a>
				    
				</div>
			</div>
		</nav>
    </header>
    
    <div class="main-wrapper">
	    	    
	    <article class="about-section py-5">
		    <div class="container">
			    <h2 class="title mb-3">About Me</h2>
			    
			    <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. </p>
			    <figure><img class="img-fluid" src="assets/images/about-me.jpg" alt="image"></figure>
			    <h5 class="mt-5">About The Blog</h5>
			    <p>Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam nunc, blandit vel, luctus pulvinar, hendrerit id, lorem. Maecenas nec odio et ante tincidunt tempus. Donec vitae sapien ut libero venenatis faucibus. Nullam quis ante. Etiam sit amet orci eget eros faucibus tincidunt. Duis leo. Sed fringilla mauris sit amet nibh. Donec sodales sagittis magna. Sed consequat, leo eget bibendum sodales, augue velit cursus nunc, quis gravida magna mi a libero. Fusce vulputate eleifend sapien. Vestibulum purus quam, scelerisque ut, mollis sed, nonummy id, metus.</p>
			    <h5 class="mt-5">My Skills and Experiences</h5>
			    <p>Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi.</p>
			    <h5 class="mt-5">Side Projects</h5>
			    <p>Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi.</p>
			    
			    <figure><a href="https://made4dev.com"><img class="img-fluid" src="assets/images/promo-banner.jpg" alt="image"></a></figure>
		    </div>
	    </article><!--//about-section-->
	    
	    <section class="cta-section theme-bg-light py-5">
		    <div class="container text-center">
			    <h2 class="heading">Newsletter</h2>
			    <div class="intro">Welcome to my blog. Subscribe and get my latest blog post in your inbox.</div>
			    <form class="signup-form form-inline justify-content-center pt-3">
                    <div class="form-group">
                        <label class="sr-only" for="semail">Your email</label>
                        <input type="email" id="semail" name="semail1" class="form-control mr-md-1 semail" placeholder="Enter email">
                    </div>
                    <button type="submit" class="btn btn-primary">Subscribe</button>
                </form>
		    </div><!--//container-->
	    </section>
	    
	    <footer class="footer text-center py-2 theme-bg-dark">
		   
	        <!--/* This template is released under the Creative Commons Attribution 3.0 License. Please keep the attribution link below when using for your own project. Thank you for your support. :) If you'd like to use the template without the attribution, you can buy the commercial license via our website: themes.3rdwavemedia.com */-->
            <small class="copyright">Designed with <i class="fas fa-heart" style="color: #fb866a;"></i> by <a href="http://themes.3rdwavemedia.com" target="_blank">Xiaoying Riley</a> for developers</small>
		   
	    </footer>
    
    </div><!--//main-wrapper-->
    

    <!-- *****CONFIGURE STYLE (REMOVE ON YOUR PRODUCTION SITE)****** -->  
    <div id="config-panel" class="config-panel d-none d-lg-block">
        <div class="panel-inner">
            <a id="config-trigger" class="config-trigger config-panel-hide text-center" href="#"><i class="fas fa-cog fa-spin mx-auto" data-fa-transform="down-6" ></i></a>
            <h5 class="panel-title">Choose Colour</h5>
            <ul id="color-options" class="list-inline mb-0">
                <li class="theme-1 active list-inline-item"><a data-style="assets/css/theme-1.css" href="#"></a></li>
                <li class="theme-2  list-inline-item"><a data-style="assets/css/theme-2.css" href="#"></a></li>
                <li class="theme-3  list-inline-item"><a data-style="assets/css/theme-3.css" href="#"></a></li>
                <li class="theme-4  list-inline-item"><a data-style="assets/css/theme-4.css" href="#"></a></li>
                <li class="theme-5  list-inline-item"><a data-style="assets/css/theme-5.css" href="#"></a></li>
                <li class="theme-6  list-inline-item"><a data-style="assets/css/theme-6.css" href="#"></a></li>
                <li class="theme-7  list-inline-item"><a data-style="assets/css/theme-7.css" href="#"></a></li>
                <li class="theme-8  list-inline-item"><a data-style="assets/css/theme-8.css" href="#"></a></li>
            </ul>
            <a id="config-close" class="close" href="#"><i class="fa fa-times-circle"></i></a>
        </div><!--//panel-inner-->
    </div><!--//configure-panel-->

    
       
    <!-- Javascript -->          
    <script src="assets/plugins/jquery-3.3.1.min.js"></script>
    <script src="assets/plugins/popper.min.js"></script> 
    <script src="assets/plugins/bootstrap/js/bootstrap.min.js"></script> 
    
    <!-- Style Switcher (REMOVE ON YOUR PRODUCTION SITE) -->
    <script src="assets/js/demo/style-switcher.js"></script>     
    

</body>
</html> 

templates/blog/categories.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <style>
        .even{
            background-color: yellow;
        }
    </style>
</head>
<body>
{% for category in categories %}
    <p class="{% if forloop.counter0|divisibleby:2 %} even {% else %} odd{% endif %}">{{ category.title }}</p>
{% endfor %}
</body>
</html>

templates/blog/detail.html
{% extends 'base.html' %}
{% load humanize static %}

{% block title %} {{ post.title }} {% endblock %}

{% block content %}
    <article class="blog-post px-3 py-5 p-md-5">
        <div class="container">
            <header class="blog-post-header">
                <h2 class="title mb-2">{{ post.title }}</h2>
                <img class="mr-3 img-fluid post-thumb d-none d-md-flex"
                     src="{{ post.thumbnail.url }}" alt="image">
                <div class="meta mb-3"><span class="date">Published {{ post.publish_time|naturaltime }}</span><span
                        class="time">5 min read</span><span class="comment"><a href="#">4 comments</a></span><a
                        href="{% url 'blog:share-post' post.pk %} ">Share</a></div>
            </header>

            <div class="blog-post-body">
                {{ post.body }}
            </div>
        <hr>
            <section>
                {% for comment in comments %}
                    <div>{{ comment.body }}</div>
                {% endfor %}
            </section>
            <section>
                {% if user.is_authenticated %}
                    <form method="post" novalidate>
                        {% csrf_token %}
                        {{ comments_form.as_table }}
                        <input type="submit" value="Send">
                    </form>
                {% else %}
                    <a href="/accounts/login">login</a>
                {% endif %}
            </section>
{#            <nav class="blog-nav nav nav-justified my-5">#}
{#                <a class="nav-link-prev nav-item nav-link rounded-left" href="index.html">Previous<i#}
{#                        class="arrow-prev fas fa-long-arrow-alt-left"></i></a>#}
{#                <a class="nav-link-next nav-item nav-link rounded-right" href="blog-list.html">Next<i#}
{#                        class="arrow-next fas fa-long-arrow-alt-right"></i></a>#}
{#            </nav>#}
{##}
{#            <div class="blog-comments-section">#}
{#                <div id="disqus_thread"></div>#}
{#                <script>#}
{#                    /**#}
{#                     *  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT#}
{#                     *  THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR#}
{#                     *  PLATFORM OR CMS.#}
{#                     *#}
{#                     *  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT:#}
{#                     *  https://disqus.com/admin/universalcode/#configuration-variables#}
{#                     */#}
{#                    /*#}
{#                    var disqus_config = function () {#}
{#                        // Replace PAGE_URL with your page's canonical URL variable#}
{#                        this.page.url = PAGE_URL;  #}
{#                        #}
{#                        // Replace PAGE_IDENTIFIER with your page's unique identifier variable#}
{#                        this.page.identifier = PAGE_IDENTIFIER; #}
{#                    };#}
{#                    */#}
{##}
{#                    (function () {  // REQUIRED CONFIGURATION VARIABLE: EDIT THE SHORTNAME BELOW#}
{#                        var d = document, s = d.createElement('script');#}
{##}
{#                        // IMPORTANT: Replace 3wmthemes with your forum shortname!#}
{#                        s.src = 'https://3wmthemes.disqus.com/embed.js';#}
{##}
{#                        s.setAttribute('data-timestamp', +new Date());#}
{#                        (d.head || d.body).appendChild(s);#}
{#                    })();#}
{#                </script>#}
{#                <noscript>#}
{#                    Please enable JavaScript to view the#}
{#                    <a href="https://disqus.com/?ref_noscript" rel="nofollow">#}
{#                        comments powered by Disqus.#}
{#                    </a>#}
{#                </noscript>#}
{#            </div><!--//blog-comments-section-->#}

        </div><!--//container-->
    </article>
{% endblock %}
{% block footerextra %}
    <script src="{% static 'assets/js/blog.js' %}"></script>
{% endblock %}

templates/blog/list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <section class="blog-list px-3 py-5 p-md-5">
        <div class="container">
            {% for item in posts %}
                <div class="item mb-5">
                    <div class="media">
                        <img class="mr-3 img-fluid post-thumb d-none d-md-flex"
                             src="{{ item.thumbnail.url }}" alt="image">
                        <div class="media-body">
                            <h3 class="title mb-1"><a href="{{ item.publish_time|date:"Y/m/d" }}/{{ item.slug }}">{{ item.title }}</a></h3>
                            <div class="meta mb-1"><span class="date">{{ item.publish_time }}</span><span class="time">5 min read</span><span
                                    class="comment"><a href="#">4 comments</a></span></div>
                            <div class="intro">{{ item.lead }}
                            </div>
                            <a class="more-link" href="{{ item.publish_time|date:'Y/m/d' }}/{{ item.slug }}">Read more
                                &rarr;</a>
                        </div><!--//media-body-->
                    </div><!--//media-->
                </div>
            {% endfor %}



            <nav class="blog-nav nav nav-justified my-5">
                <a class="nav-link-prev nav-item nav-link rounded-left" href="list.html">Previous<i
                        class="arrow-prev fas fa-long-arrow-alt-left"></i></a>
                <a class="nav-link-next nav-item nav-link rounded-right" href="blog-list.html">Next<i
                        class="arrow-next fas fa-long-arrow-alt-right"></i></a>
            </nav>

        </div>
    </section>
{% endblock %}

templates/blog/share.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
Article : {{ post.title }}
<form method="post">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit" value="Share ">
</form>
</body>
</html>

templates/footer.html
{% load static %}
<!-- Javascript -->
<script src="{% static 'assets/plugins/jquery-3.3.1.min.js' %}"></script>
<script src="{% static 'assets/plugins/popper.min.js' %}"></script>
<script src="{% static 'assets/plugins/bootstrap/js/bootstrap.min.js' %}"></script>

<!-- Style Switcher (REMOVE ON YOUR PRODUCTION SITE) -->
<script src="{% static 'assets/js/demo/style-switcher.js' %}"></script>

templates/header.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>